name: Update Card Data

on:
  schedule:
    # Run at 6 AM and 6 PM UTC (twice daily)
    - cron: '0 6,18 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-cards:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup database
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run card update script
        run: npm run update-cards
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Commit database changes (if any)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add prisma/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update card data from Scryfall"
        continue-on-error: true 